### PR TITLE
Go Module Setup

### PR DESCRIPTION
**Pull request by jumaallan**
I was playing around with this repo, and decided to introduce go module. If this still works, I would also love to help maintain/build new features as well 🚀

### CODE REVIEW

**Review by davkutalek — COMMENTED** [review]
@jumaallan I'm not very familiar with go, so can't really give feedback. Feel free to update this, though it obviously isn't high priority since it is a developer tool and that isn't our focus at the moment.

**Comment by ishuah** [comment]
@jumaallan just saw this, will review it in the morning

**Review by ishuah — APPROVED** [review]
LGTM!

**Comment by ishuah** [comment]
@jumaallan approved! I'll leave the 'merge to base branch' honor to you.

**Comment by jumaallan** [comment]
> @jumaallan approved! I'll leave the 'merge to base branch' honor to you.

🚀

**Pull request merged**
